[View in Colaboratory](https://colab.research.google.com/github/lcckkkhaha/ML-basic/blob/master/Network.ipynb)

In [4]:
import numpy as np
import random

class Network():
  def __init__(self,structure):
    self.number_of_layers=len(structure)
    self.structure=structure
    self.biases=[np.random.randn(i,1) for i in structure[1:]]
    self.weights=[np.random.randn(i,j) for i,j in [structure[:-1],structure[1:]]]
    #self.weights=np.transpose(self.weights)
    
  def sigmoid(self,X):
    X=1/(1+np.exp(X))
    return X
  
  
  def feedforward(self,layer_input):
    for w,b in [self.weights,self.biases]:
      w=np.transpose(w)
      print("weight:",w,"shape:",w.shape)
      print("biases:",b)
      print("layer_input:",layer_input,"shape:",layer_input.shape)
      #print("dot:",np.dot(w,layer_input))
      temp =np.dot(w,layer_input) + b
      print("output:",temp)
      layer_input=self.sigmoid(temp)
      print("sigmoid:",layer_input)
      #print(layer_input)
    return layer_input
   
    def SGD(self, train_data, epochs, mini_batch_size, eta, test_data):
      n=len(train_data)
      for i in range(0,epochs):
        print("Epochs:",i)
        random.shuffle(train_data)
        mini_batches=[train_data[k:k+mini_batch-size] for k in range(0,n,mini_batch_size)]
        for mini_batch in mini_batches:
          self.update_mini_batch(mini_batch,eta)

    def update_mini_batch(self,mini_batch,eta):
      
      
                
structure=[3,4,1]    
net=Network(structure)
#print("structure:",net.structure)
#print("weight:",net.weights)
#print("biases:",net.biases)

net.feedforward(np.array([[5],[6],[7]]))

#print([structure[:-1],structure[1:]])


weight: [[ 0.45335191  1.75053131  0.91828593]
 [-0.57862119  1.30531401 -0.34312026]
 [ 0.13822012  0.43899456 -0.12557966]
 [-1.26617759  0.53896132 -1.29065438]] shape: (4, 3)
biases: [[-0.55546659]
 [-1.53127129]
 [ 1.01410753]
 [-0.70095275]]
layer_input: [[5]
 [6]
 [7]] shape: (3, 1)
output: [[ 18.64248234]
 [  1.00566495]
 [  3.46011786]
 [-12.83265342]]
sigmoid: [[8.01074276e-09]
 [2.67829084e-01]
 [3.04685515e-02]
 [9.99997328e-01]]
weight: [[ 1.47863568  0.44692892 -0.40882572  0.48342614]] shape: (1, 4)
biases: [[-1.12878152]]
layer_input: [[8.01074276e-09]
 [2.67829084e-01]
 [3.04685515e-02]
 [9.99997328e-01]] shape: (4, 1)
output: [[-0.53811242]]
sigmoid: [[0.63137321]]


array([[0.63137321]])